name: getpocket
description: light weight getpocket client.
publish_to: 'none'
version: 1.1.0-dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  url_launcher: ^6.1.5
  shared_preferences: ^2.0.15
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.0.0-dev.9
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.4.0
  build_runner: ^2.2.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: false
  ios: true
  image_path: "android/app/src/main/ic_launcher-playstore.png"
