name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - name: pub get
        run: flutter pub get
      - run: echo "${{secrets.ANDROID_RELEASE_BASE64_KEY}}" | base64 -d > ./keystore.jks
      - run: echo "keyAlias=keystore" >> android/key.properties
      - run: echo "keyPassword=${{secrets.ANDROID_RELEASE_KEY_PASSWORD}}" >> android/key.properties
      - run: echo "storeFile=`pwd`/keystore.jks" >> android/key.properties
      - run: echo "storePassword=${{secrets.ANDROID_RELEASE_STORE_PASSWORD}}" >> android/key.properties
      - name: build apk
        run: flutter build apk --release --build-number ${GITHUB_RUN_NUMBER} --dart-define=POCKET_CONSUMER_KEY=${{secrets.POCKET_CONSUMER_KEY}} --dart-define=POCKET_REDIRECT_URI=${{secrets.POCKET_REDIRECT_URI}}
      - name: deploygate
        if: ${{ !contains(github.head_ref, 'release') }}
        run: |
          curl \
          -H "Authorization: token ${{secrets.DEPLOYGATE_API_KEY}}" \
          -F "file=@build/app/outputs/flutter-apk/app-release.apk" \
          "https://deploygate.com/api/users/yuzumone/apps"
      - name: deploygate and update distribution
        if: ${{ contains(github.head_ref, 'release') }}
        run: |
          curl \
          -H "Authorization: token ${{secrets.DEPLOYGATE_API_KEY}}" \
          -F "file=@build/app/outputs/flutter-apk/app-release.apk" \
          --form-string "distribution_key=01f49cf8bc4bb409581290648c3303df8a47385f" \
          "https://deploygate.com/api/users/yuzumone/apps"
